name: Build Chess APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      # هنا السر: أخبرنا GitHub أن يدخل لمجلد المشروع أولاً
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./chess_projct

      - name: Build with Gradle
        run: ./gradlew assembleDebug
        working-directory: ./chess_projct

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: chess-app
          path: chess_projct/app/build/outputs/apk/debug/app-debug.apk
