name: Build Chess APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # تأكد من أننا نستخدم النسخة الصحيحة من Gradle داخل المجلد
      - name: Grant execute permission for gradlew
        run: chmod +x ./chess_projct/gradlew

      # التشغيل من المجلد الرئيسي مع تحديد مسار المشروع
      - name: Build with Gradle
        run: ./chess_projct/gradlew assembleDebug -p ./chess_projct
